# Generated by Django 3.0.7 on 2020-06-06 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generales', '0002_auto_20200606_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attrcategoria',
            name='campo',
            field=models.CharField(choices=[('int', 'Numerico'), ('str', 'Cadena'), ('sel', 'Selector')], max_length=5),
        ),
        migrations.AlterField(
            model_name='materiales',
            name='unidad_de_medida',
            field=models.CharField(choices=[('g', 'gramo/s'), ('k', 'kilo/s'), ('cm2', 'centimetro/ cuadrado/s'), ('cm', 'centimetro/s'), ('m', 'metros'), ('mm', 'milimetros')], default='g', max_length=5),
        ),
    ]
