# Generated by Django 3.0.7 on 2020-06-06 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generales', '0003_auto_20200606_1947'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='medida3',
            new_name='medida1_int',
        ),
        migrations.AddField(
            model_name='categoria',
            name='caras',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='categoria',
            name='forma',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='categoria',
            name='medida1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='categoria',
            name='medida1_ext',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='categoria',
            name='medida1_int',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='categoria',
            name='medida2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='categoria',
            name='medida2_ext',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='categoria',
            name='medida2_int',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='categoria',
            name='peso',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='caras',
            field=models.CharField(choices=[('s', 'simple'), ('d', 'doble')], default=1, max_length=5),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='AttrCategoria',
        ),
    ]
