# Generated by Django 3.0.7 on 2020-06-06 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generales', '0004_auto_20200606_2020'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='medida1_ext',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='medida2_ext',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='medida2_int',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5),
            preserve_default=False,
        ),
    ]
