# Generated by Django 3.0.7 on 2020-06-06 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generales', '0005_auto_20200606_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='medida1',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='producto',
            name='medida1_ext',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='producto',
            name='medida1_int',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='producto',
            name='medida2',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='producto',
            name='medida2_ext',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='producto',
            name='medida2_int',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5),
        ),
    ]
