# Generated by Django 3.0.7 on 2020-06-06 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generales', '0006_auto_20200606_2158'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='color',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='producto',
            name='color',
            field=models.CharField(blank=True, max_length=400),
        ),
    ]
