# Generated by Django 3.0.7 on 2020-06-07 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generales', '0007_auto_20200606_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='forma',
            field=models.CharField(choices=[('circ', 'Circular'), ('rect', 'Rectangular'), ('cuad', 'Cuadrado'), ('irre', 'Irregular'), ('tria', 'Triangular'), ('oval', 'Ovalada'), ('cruz', 'Cruz')], max_length=5),
        ),
    ]
