# Generated by Django 3.0.7 on 2020-06-07 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generales', '0010_rango_precios'),
    ]

    operations = [
        migrations.CreateModel(
            name='porcetaje_por_rango',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso_minimo', models.FloatField()),
                ('peso_maximo', models.FloatField()),
                ('porcentual', models.FloatField()),
            ],
        ),
    ]
