# Generated by Django 3.0.7 on 2020-06-07 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generales', '0011_porcetaje_por_rango'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='porcetaje_por_rango',
            new_name='porcentaje_por_rango',
        ),
    ]
