# Generated by Django 3.0.7 on 2020-06-07 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generales', '0012_auto_20200607_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='porcentaje_por_rango',
            name='categoria_ml',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='porcentaje_por_rango',
            name='categoria_presta',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
