# Generated by Django 3.0.7 on 2020-06-07 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generales', '0017_rango_precios_material'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rango_precios',
            name='material',
        ),
        migrations.AlterField(
            model_name='materiales',
            name='costo',
            field=models.FloatField(),
        ),
    ]
