# Generated by Django 3.0.7 on 2020-06-07 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generales', '0018_auto_20200607_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='categoria_ml',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='categoria',
            name='categoria_presta',
            field=models.IntegerField(default=16),
        ),
    ]
