# Generated by Django 3.0.7 on 2020-06-21 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PrestaConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre identificador de la configuración del sitio que contiene la API', max_length=20, unique=True)),
                ('host', models.CharField(help_text='Host donde se aloja la API, ejemplo: localhost.com', max_length=150)),
                ('protocol', models.CharField(choices=[('http', 'http'), ('https', 'https')], default='http', help_text='Protocolo por el cual el host responde.', max_length=10)),
                ('key', models.CharField(help_text='Key generada por la API de Prestashop.', max_length=50)),
                ('active', models.BooleanField(help_text='Si el registro se encuentra activo.')),
                ('default', models.BooleanField(default=False, help_text='El campo que este en true será el que se tome.')),
            ],
        ),
    ]
